apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "priorityclass-webhook.fullname" . }}
  labels:
    {{- include "priorityclass-webhook.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "priorityclass-webhook.fullname" . }}
  labels:
    {{- include "priorityclass-webhook.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "priorityclass-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "priorityclass-webhook.fullname" . }}
  apiGroup: rbac.authorization.k8s.io