apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "priorityclass-webhook.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "priorityclass-webhook.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "priorityclass-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "priorityclass-webhook.fullname" . }}
  apiGroup: rbac.authorization.k8s.io