---
# Verify priorityClassName doesn't get set on pods
apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    app: nginx
    foo: bar
  annotations:
    testAnnotation: used-for-testing-purposes-priority
spec:
  containers:
  - name: nginx
    image: nginx
---
# Verify priorityClassName get set on DaemonSets
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-2
  labels:
    app: nginx
    foo: bar
  annotations:
    testAnnotation: used-for-testing-purposes-priority
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
# Verify priorityClassName get set on DaemonSets with priorityClassName already set
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-3
  labels:
    app: nginx
    foo: bar
  annotations:
    testAnnotation: used-for-testing-purposes-priority
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      priorityClassName: system-cluster-critical
---
# Verify priorityClassName does not get set on DaemonSets with priorityClassName already set to high-priority-nonpreempting
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-4
  labels:
    app: nginx
    foo: bar
  annotations:
    testAnnotation: used-for-testing-purposes-priority
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      priorityClassName: high-priority-nonpreempting
---
# Verify priorityClassName does not get set on DaemonSets without match labels
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-5
  labels:
    app: nginx
  annotations:
    testAnnotation: used-for-testing-purposes-priority
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80