apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-1
  labels:
    app: nginx
    foo: bar
  annotations:
    testAnnotation: used-for-testing-purposes-priority
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
